// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7R0DmIqK5uefoFXhMG9PM0XSyUk7Z8sc',
    appId: '1:1010420009793:android:3a8363b197d786b1af2fc0',
    messagingSenderId: '1010420009793',
    projectId: 'taxi-app-user-4800a',
    storageBucket: 'taxi-app-user-4800a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0gp6JLrfczDndptY0k2g5IrtNDhDO60c',
    appId: '1:1010420009793:ios:31709cf9b416db78af2fc0',
    messagingSenderId: '1010420009793',
    projectId: 'taxi-app-user-4800a',
    storageBucket: 'taxi-app-user-4800a.appspot.com',
    androidClientId: '1010420009793-04b92isf592qg9jotmgbeb7133d42obk.apps.googleusercontent.com',
    iosClientId: '1010420009793-e95hpundp60mqied0569t44rp0scg05h.apps.googleusercontent.com',
    iosBundleId: 'com.syloops.wigoouser',
  );
}
