// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcUiq4ME8Hc3N7nsoDs0YYC2e4nWwyghU',
    appId: '1:1010420009793:web:7cda7afe785a3d61af2fc0',
    messagingSenderId: '1010420009793',
    projectId: 'taxi-app-user-4800a',
    authDomain: 'taxi-app-user-4800a.firebaseapp.com',
    storageBucket: 'taxi-app-user-4800a.appspot.com',
    measurementId: 'G-FB7HH2MCY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7R0DmIqK5uefoFXhMG9PM0XSyUk7Z8sc',
    appId: '1:1010420009793:android:3b4d2a9c15202124af2fc0',
    messagingSenderId: '1010420009793',
    projectId: 'taxi-app-user-4800a',
    storageBucket: 'taxi-app-user-4800a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0gp6JLrfczDndptY0k2g5IrtNDhDO60c',
    appId: '1:1010420009793:ios:f61d5103fd58cf7caf2fc0',
    messagingSenderId: '1010420009793',
    projectId: 'taxi-app-user-4800a',
    storageBucket: 'taxi-app-user-4800a.appspot.com',
    androidClientId: '1010420009793-ic7djdcuk8ijujdrdcovq9hkhlqcs3r8.apps.googleusercontent.com',
    iosClientId: '1010420009793-heipnrg7m79gtbl2e5um2gbllip3rpna.apps.googleusercontent.com',
    iosBundleId: 'com.example.witgootaxiuser',
  );
}
